#define DISPLAY_SDA_PIN 5
#define DISPLAY_SCL_PIN 4
#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64
#define ROTARY_DATA_PIN 15
#define ROTARY_CLK_PIN 13
#define ROTARY_BUTTON_PIN 2

#define UI_MAIN 0
#define UI_MOTOR_SELECT 1
#define UI_TUNE 2
#define UI_OPTIONS 3
#define UI_OPT_CONNECT 4
#define UI_OPT_IDLE 5

#define LEFT_SEAT 1
#define RIGHT_SEAT 2

#define MOTOR_ANGLE 1
#define MOTOR_FORWARD 2
#define MOTOR_HEAD 3
#define MOTOR_HZ1 4
#define MOTOR_HZ2 5